// Generated by gencpp from file lidapy_rosdeps/ccqGetLastNBroadcasts.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_CCQGETLASTNBROADCASTS_H
#define LIDAPY_ROSDEPS_MESSAGE_CCQGETLASTNBROADCASTS_H

#include <ros/service_traits.h>


#include <lidapy_rosdeps/ccqGetLastNBroadcastsRequest.h>
#include <lidapy_rosdeps/ccqGetLastNBroadcastsResponse.h>


namespace lidapy_rosdeps
{

struct ccqGetLastNBroadcasts
{

typedef ccqGetLastNBroadcastsRequest Request;
typedef ccqGetLastNBroadcastsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ccqGetLastNBroadcasts
} // namespace lidapy_rosdeps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcasts > {
  static const char* value()
  {
    return "df37d1ef5e33d91e61fb506ae6de16eb";
  }

  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcasts&) { return value(); }
};

template<>
struct DataType< ::lidapy_rosdeps::ccqGetLastNBroadcasts > {
  static const char* value()
  {
    return "lidapy_rosdeps/ccqGetLastNBroadcasts";
  }

  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcasts&) { return value(); }
};


// service_traits::MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcasts > 
template<>
struct MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest> should match 
// service_traits::DataType< ::lidapy_rosdeps::ccqGetLastNBroadcasts > 
template<>
struct DataType< ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcastsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcasts > 
template<>
struct MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse> should match 
// service_traits::DataType< ::lidapy_rosdeps::ccqGetLastNBroadcasts > 
template<>
struct DataType< ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::lidapy_rosdeps::ccqGetLastNBroadcastsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_CCQGETLASTNBROADCASTS_H
