// Generated by gencpp from file lidapy_rosdeps/CognitiveContent.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_COGNITIVECONTENT_H
#define LIDAPY_ROSDEPS_MESSAGE_COGNITIVECONTENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidapy_rosdeps/KeyValues.h>

namespace lidapy_rosdeps
{
template <class ContainerAllocator>
struct CognitiveContent_
{
  typedef CognitiveContent_<ContainerAllocator> Type;

  CognitiveContent_()
    : header()
    , elements()  {
    }
  CognitiveContent_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , elements(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lidapy_rosdeps::KeyValues_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidapy_rosdeps::KeyValues_<ContainerAllocator> >::other >  _elements_type;
  _elements_type elements;




  typedef boost::shared_ptr< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> const> ConstPtr;

}; // struct CognitiveContent_

typedef ::lidapy_rosdeps::CognitiveContent_<std::allocator<void> > CognitiveContent;

typedef boost::shared_ptr< ::lidapy_rosdeps::CognitiveContent > CognitiveContentPtr;
typedef boost::shared_ptr< ::lidapy_rosdeps::CognitiveContent const> CognitiveContentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidapy_rosdeps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lidapy_rosdeps': ['/home/stephen/Development/ccrg/Cryptoquip/src/lidapy_rosdeps/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f91efa81b1a0fe4b205d5da835c13b";
  }

  static const char* value(const ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f91efa81b1a0feULL;
  static const uint64_t static_value2 = 0x4b205d5da835c13bULL;
};

template<class ContainerAllocator>
struct DataType< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidapy_rosdeps/CognitiveContent";
  }

  static const char* value(const ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
KeyValues[] elements\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lidapy_rosdeps/KeyValues\n\
string key\n\
string[] values\n\
";
  }

  static const char* value(const ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.elements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CognitiveContent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidapy_rosdeps::KeyValues_<ContainerAllocator> >::stream(s, indent + "    ", v.elements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_COGNITIVECONTENT_H
