// Generated by gencpp from file lidapy_rosdeps/csmAddContent.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_CSMADDCONTENT_H
#define LIDAPY_ROSDEPS_MESSAGE_CSMADDCONTENT_H

#include <ros/service_traits.h>


#include <lidapy_rosdeps/csmAddContentRequest.h>
#include <lidapy_rosdeps/csmAddContentResponse.h>


namespace lidapy_rosdeps
{

struct csmAddContent
{

typedef csmAddContentRequest Request;
typedef csmAddContentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct csmAddContent
} // namespace lidapy_rosdeps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidapy_rosdeps::csmAddContent > {
  static const char* value()
  {
    return "c65617913ec357532e90aa89ea8db840";
  }

  static const char* value(const ::lidapy_rosdeps::csmAddContent&) { return value(); }
};

template<>
struct DataType< ::lidapy_rosdeps::csmAddContent > {
  static const char* value()
  {
    return "lidapy_rosdeps/csmAddContent";
  }

  static const char* value(const ::lidapy_rosdeps::csmAddContent&) { return value(); }
};


// service_traits::MD5Sum< ::lidapy_rosdeps::csmAddContentRequest> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmAddContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmAddContentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmAddContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmAddContentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmAddContentRequest> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmAddContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmAddContentRequest>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmAddContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmAddContentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidapy_rosdeps::csmAddContentResponse> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmAddContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmAddContentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmAddContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmAddContentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmAddContentResponse> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmAddContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmAddContentResponse>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmAddContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmAddContentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_CSMADDCONTENT_H
