// Generated by gencpp from file lidapy_rosdeps/csmFindContentResponse.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_CSMFINDCONTENTRESPONSE_H
#define LIDAPY_ROSDEPS_MESSAGE_CSMFINDCONTENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lidapy_rosdeps/CognitiveContent.h>

namespace lidapy_rosdeps
{
template <class ContainerAllocator>
struct csmFindContentResponse_
{
  typedef csmFindContentResponse_<ContainerAllocator> Type;

  csmFindContentResponse_()
    : found_content()  {
    }
  csmFindContentResponse_(const ContainerAllocator& _alloc)
    : found_content(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >::other >  _found_content_type;
  _found_content_type found_content;




  typedef boost::shared_ptr< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct csmFindContentResponse_

typedef ::lidapy_rosdeps::csmFindContentResponse_<std::allocator<void> > csmFindContentResponse;

typedef boost::shared_ptr< ::lidapy_rosdeps::csmFindContentResponse > csmFindContentResponsePtr;
typedef boost::shared_ptr< ::lidapy_rosdeps::csmFindContentResponse const> csmFindContentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidapy_rosdeps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lidapy_rosdeps': ['/home/stephen/Development/ccrg/Cryptoquip/src/lidapy_rosdeps/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "959d9b9274f8aad9e52e80098a754217";
  }

  static const char* value(const ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x959d9b9274f8aad9ULL;
  static const uint64_t static_value2 = 0xe52e80098a754217ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidapy_rosdeps/csmFindContentResponse";
  }

  static const char* value(const ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CognitiveContent[] found_content\n\
\n\
\n\
================================================================================\n\
MSG: lidapy_rosdeps/CognitiveContent\n\
Header header\n\
KeyValues[] elements\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lidapy_rosdeps/KeyValues\n\
string key\n\
string[] values\n\
";
  }

  static const char* value(const ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found_content);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct csmFindContentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidapy_rosdeps::csmFindContentResponse_<ContainerAllocator>& v)
  {
    s << indent << "found_content[]" << std::endl;
    for (size_t i = 0; i < v.found_content.size(); ++i)
    {
      s << indent << "  found_content[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidapy_rosdeps::CognitiveContent_<ContainerAllocator> >::stream(s, indent + "    ", v.found_content[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_CSMFINDCONTENTRESPONSE_H
