// Generated by gencpp from file lidapy_rosdeps/csmListContent.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_CSMLISTCONTENT_H
#define LIDAPY_ROSDEPS_MESSAGE_CSMLISTCONTENT_H

#include <ros/service_traits.h>


#include <lidapy_rosdeps/csmListContentRequest.h>
#include <lidapy_rosdeps/csmListContentResponse.h>


namespace lidapy_rosdeps
{

struct csmListContent
{

typedef csmListContentRequest Request;
typedef csmListContentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct csmListContent
} // namespace lidapy_rosdeps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidapy_rosdeps::csmListContent > {
  static const char* value()
  {
    return "03e4330075f540fcfbaafbb883d34643";
  }

  static const char* value(const ::lidapy_rosdeps::csmListContent&) { return value(); }
};

template<>
struct DataType< ::lidapy_rosdeps::csmListContent > {
  static const char* value()
  {
    return "lidapy_rosdeps/csmListContent";
  }

  static const char* value(const ::lidapy_rosdeps::csmListContent&) { return value(); }
};


// service_traits::MD5Sum< ::lidapy_rosdeps::csmListContentRequest> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmListContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmListContentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmListContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmListContentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmListContentRequest> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmListContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmListContentRequest>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmListContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmListContentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidapy_rosdeps::csmListContentResponse> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmListContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmListContentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmListContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmListContentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmListContentResponse> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmListContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmListContentResponse>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmListContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmListContentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_CSMLISTCONTENT_H
