// Generated by gencpp from file lidapy_rosdeps/csmUpdateContent.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_CSMUPDATECONTENT_H
#define LIDAPY_ROSDEPS_MESSAGE_CSMUPDATECONTENT_H

#include <ros/service_traits.h>


#include <lidapy_rosdeps/csmUpdateContentRequest.h>
#include <lidapy_rosdeps/csmUpdateContentResponse.h>


namespace lidapy_rosdeps
{

struct csmUpdateContent
{

typedef csmUpdateContentRequest Request;
typedef csmUpdateContentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct csmUpdateContent
} // namespace lidapy_rosdeps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidapy_rosdeps::csmUpdateContent > {
  static const char* value()
  {
    return "b5c6fc7694e25a71c58a14b8a055ecb1";
  }

  static const char* value(const ::lidapy_rosdeps::csmUpdateContent&) { return value(); }
};

template<>
struct DataType< ::lidapy_rosdeps::csmUpdateContent > {
  static const char* value()
  {
    return "lidapy_rosdeps/csmUpdateContent";
  }

  static const char* value(const ::lidapy_rosdeps::csmUpdateContent&) { return value(); }
};


// service_traits::MD5Sum< ::lidapy_rosdeps::csmUpdateContentRequest> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmUpdateContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmUpdateContentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmUpdateContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmUpdateContentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmUpdateContentRequest> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmUpdateContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmUpdateContentRequest>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmUpdateContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmUpdateContentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidapy_rosdeps::csmUpdateContentResponse> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::csmUpdateContent > 
template<>
struct MD5Sum< ::lidapy_rosdeps::csmUpdateContentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::csmUpdateContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmUpdateContentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::csmUpdateContentResponse> should match 
// service_traits::DataType< ::lidapy_rosdeps::csmUpdateContent > 
template<>
struct DataType< ::lidapy_rosdeps::csmUpdateContentResponse>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::csmUpdateContent >::value();
  }
  static const char* value(const ::lidapy_rosdeps::csmUpdateContentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_CSMUPDATECONTENT_H
