// Generated by gencpp from file lidapy_rosdeps/decayModuleRequest.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_DECAYMODULEREQUEST_H
#define LIDAPY_ROSDEPS_MESSAGE_DECAYMODULEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidapy_rosdeps
{
template <class ContainerAllocator>
struct decayModuleRequest_
{
  typedef decayModuleRequest_<ContainerAllocator> Type;

  decayModuleRequest_()
    : n(0)
    , strategy()  {
    }
  decayModuleRequest_(const ContainerAllocator& _alloc)
    : n(0)
    , strategy(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _n_type;
  _n_type n;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strategy_type;
  _strategy_type strategy;




  typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct decayModuleRequest_

typedef ::lidapy_rosdeps::decayModuleRequest_<std::allocator<void> > decayModuleRequest;

typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleRequest > decayModuleRequestPtr;
typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleRequest const> decayModuleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidapy_rosdeps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lidapy_rosdeps': ['/home/stephen/Development/ccrg/Cryptoquip/src/lidapy_rosdeps/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "427a4bc49879904c5ed779ad55d5bbc8";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x427a4bc49879904cULL;
  static const uint64_t static_value2 = 0x5ed779ad55d5bbc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidapy_rosdeps/decayModuleRequest";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 n\n\
string strategy\n\
";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n);
      stream.next(m.strategy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct decayModuleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidapy_rosdeps::decayModuleRequest_<ContainerAllocator>& v)
  {
    s << indent << "n: ";
    Printer<int8_t>::stream(s, indent + "  ", v.n);
    s << indent << "strategy: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strategy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_DECAYMODULEREQUEST_H
