// Generated by gencpp from file lidapy_rosdeps/decayModule.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_DECAYMODULE_H
#define LIDAPY_ROSDEPS_MESSAGE_DECAYMODULE_H

#include <ros/service_traits.h>


#include <lidapy_rosdeps/decayModuleRequest.h>
#include <lidapy_rosdeps/decayModuleResponse.h>


namespace lidapy_rosdeps
{

struct decayModule
{

typedef decayModuleRequest Request;
typedef decayModuleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct decayModule
} // namespace lidapy_rosdeps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidapy_rosdeps::decayModule > {
  static const char* value()
  {
    return "427a4bc49879904c5ed779ad55d5bbc8";
  }

  static const char* value(const ::lidapy_rosdeps::decayModule&) { return value(); }
};

template<>
struct DataType< ::lidapy_rosdeps::decayModule > {
  static const char* value()
  {
    return "lidapy_rosdeps/decayModule";
  }

  static const char* value(const ::lidapy_rosdeps::decayModule&) { return value(); }
};


// service_traits::MD5Sum< ::lidapy_rosdeps::decayModuleRequest> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::decayModule > 
template<>
struct MD5Sum< ::lidapy_rosdeps::decayModuleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::decayModule >::value();
  }
  static const char* value(const ::lidapy_rosdeps::decayModuleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::decayModuleRequest> should match 
// service_traits::DataType< ::lidapy_rosdeps::decayModule > 
template<>
struct DataType< ::lidapy_rosdeps::decayModuleRequest>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::decayModule >::value();
  }
  static const char* value(const ::lidapy_rosdeps::decayModuleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidapy_rosdeps::decayModuleResponse> should match 
// service_traits::MD5Sum< ::lidapy_rosdeps::decayModule > 
template<>
struct MD5Sum< ::lidapy_rosdeps::decayModuleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidapy_rosdeps::decayModule >::value();
  }
  static const char* value(const ::lidapy_rosdeps::decayModuleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidapy_rosdeps::decayModuleResponse> should match 
// service_traits::DataType< ::lidapy_rosdeps::decayModule > 
template<>
struct DataType< ::lidapy_rosdeps::decayModuleResponse>
{
  static const char* value()
  {
    return DataType< ::lidapy_rosdeps::decayModule >::value();
  }
  static const char* value(const ::lidapy_rosdeps::decayModuleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_DECAYMODULE_H
