// Generated by gencpp from file lidapy_rosdeps/decayModuleResponse.msg
// DO NOT EDIT!


#ifndef LIDAPY_ROSDEPS_MESSAGE_DECAYMODULERESPONSE_H
#define LIDAPY_ROSDEPS_MESSAGE_DECAYMODULERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidapy_rosdeps
{
template <class ContainerAllocator>
struct decayModuleResponse_
{
  typedef decayModuleResponse_<ContainerAllocator> Type;

  decayModuleResponse_()
    {
    }
  decayModuleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct decayModuleResponse_

typedef ::lidapy_rosdeps::decayModuleResponse_<std::allocator<void> > decayModuleResponse;

typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleResponse > decayModuleResponsePtr;
typedef boost::shared_ptr< ::lidapy_rosdeps::decayModuleResponse const> decayModuleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidapy_rosdeps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lidapy_rosdeps': ['/home/stephen/Development/ccrg/Cryptoquip/src/lidapy_rosdeps/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidapy_rosdeps/decayModuleResponse";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct decayModuleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lidapy_rosdeps::decayModuleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LIDAPY_ROSDEPS_MESSAGE_DECAYMODULERESPONSE_H
