// Generated by gencpp from file cqlida/ccqGetLastNBroadcasts.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CCQGETLASTNBROADCASTS_H
#define CQLIDA_MESSAGE_CCQGETLASTNBROADCASTS_H

#include <ros/service_traits.h>


#include <cqlida/ccqGetLastNBroadcastsRequest.h>
#include <cqlida/ccqGetLastNBroadcastsResponse.h>


namespace cqlida
{

struct ccqGetLastNBroadcasts
{

typedef ccqGetLastNBroadcastsRequest Request;
typedef ccqGetLastNBroadcastsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ccqGetLastNBroadcasts
} // namespace cqlida


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cqlida::ccqGetLastNBroadcasts > {
  static const char* value()
  {
    return "df37d1ef5e33d91e61fb506ae6de16eb";
  }

  static const char* value(const ::cqlida::ccqGetLastNBroadcasts&) { return value(); }
};

template<>
struct DataType< ::cqlida::ccqGetLastNBroadcasts > {
  static const char* value()
  {
    return "cqlida/ccqGetLastNBroadcasts";
  }

  static const char* value(const ::cqlida::ccqGetLastNBroadcasts&) { return value(); }
};


// service_traits::MD5Sum< ::cqlida::ccqGetLastNBroadcastsRequest> should match 
// service_traits::MD5Sum< ::cqlida::ccqGetLastNBroadcasts > 
template<>
struct MD5Sum< ::cqlida::ccqGetLastNBroadcastsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cqlida::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::cqlida::ccqGetLastNBroadcastsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cqlida::ccqGetLastNBroadcastsRequest> should match 
// service_traits::DataType< ::cqlida::ccqGetLastNBroadcasts > 
template<>
struct DataType< ::cqlida::ccqGetLastNBroadcastsRequest>
{
  static const char* value()
  {
    return DataType< ::cqlida::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::cqlida::ccqGetLastNBroadcastsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cqlida::ccqGetLastNBroadcastsResponse> should match 
// service_traits::MD5Sum< ::cqlida::ccqGetLastNBroadcasts > 
template<>
struct MD5Sum< ::cqlida::ccqGetLastNBroadcastsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cqlida::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::cqlida::ccqGetLastNBroadcastsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cqlida::ccqGetLastNBroadcastsResponse> should match 
// service_traits::DataType< ::cqlida::ccqGetLastNBroadcasts > 
template<>
struct DataType< ::cqlida::ccqGetLastNBroadcastsResponse>
{
  static const char* value()
  {
    return DataType< ::cqlida::ccqGetLastNBroadcasts >::value();
  }
  static const char* value(const ::cqlida::ccqGetLastNBroadcastsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CQLIDA_MESSAGE_CCQGETLASTNBROADCASTS_H
