// Generated by gencpp from file cqlida/csmAddContentResponse.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CSMADDCONTENTRESPONSE_H
#define CQLIDA_MESSAGE_CSMADDCONTENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cqlida/KeyValues.h>

namespace cqlida
{
template <class ContainerAllocator>
struct csmAddContentResponse_
{
  typedef csmAddContentResponse_<ContainerAllocator> Type;

  csmAddContentResponse_()
    : results()  {
    }
  csmAddContentResponse_(const ContainerAllocator& _alloc)
    : results(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cqlida::KeyValues_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cqlida::KeyValues_<ContainerAllocator> >::other >  _results_type;
  _results_type results;




  typedef boost::shared_ptr< ::cqlida::csmAddContentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cqlida::csmAddContentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct csmAddContentResponse_

typedef ::cqlida::csmAddContentResponse_<std::allocator<void> > csmAddContentResponse;

typedef boost::shared_ptr< ::cqlida::csmAddContentResponse > csmAddContentResponsePtr;
typedef boost::shared_ptr< ::cqlida::csmAddContentResponse const> csmAddContentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cqlida::csmAddContentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cqlida::csmAddContentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cqlida

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'cqlida': ['/home/stephen/Development/ccrg/Cryptoquip/src/cqlida/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmAddContentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmAddContentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmAddContentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf3e973cc239e9103177bd5f1fb428e6";
  }

  static const char* value(const ::cqlida::csmAddContentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf3e973cc239e910ULL;
  static const uint64_t static_value2 = 0x3177bd5f1fb428e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/csmAddContentResponse";
  }

  static const char* value(const ::cqlida::csmAddContentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/KeyValues[] results\n\
\n\
\n\
================================================================================\n\
MSG: cqlida/KeyValues\n\
string key\n\
string[] values\n\
";
  }

  static const char* value(const ::cqlida::csmAddContentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct csmAddContentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cqlida::csmAddContentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cqlida::csmAddContentResponse_<ContainerAllocator>& v)
  {
    s << indent << "results[]" << std::endl;
    for (size_t i = 0; i < v.results.size(); ++i)
    {
      s << indent << "  results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cqlida::KeyValues_<ContainerAllocator> >::stream(s, indent + "    ", v.results[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CQLIDA_MESSAGE_CSMADDCONTENTRESPONSE_H
