// Generated by gencpp from file cqlida/csmListContentRequest.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CSMLISTCONTENTREQUEST_H
#define CQLIDA_MESSAGE_CSMLISTCONTENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cqlida
{
template <class ContainerAllocator>
struct csmListContentRequest_
{
  typedef csmListContentRequest_<ContainerAllocator> Type;

  csmListContentRequest_()
    : max_results(0)  {
    }
  csmListContentRequest_(const ContainerAllocator& _alloc)
    : max_results(0)  {
  (void)_alloc;
    }



   typedef int32_t _max_results_type;
  _max_results_type max_results;




  typedef boost::shared_ptr< ::cqlida::csmListContentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cqlida::csmListContentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct csmListContentRequest_

typedef ::cqlida::csmListContentRequest_<std::allocator<void> > csmListContentRequest;

typedef boost::shared_ptr< ::cqlida::csmListContentRequest > csmListContentRequestPtr;
typedef boost::shared_ptr< ::cqlida::csmListContentRequest const> csmListContentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cqlida::csmListContentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cqlida::csmListContentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cqlida

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'cqlida': ['/home/stephen/Development/ccrg/Cryptoquip/src/cqlida/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmListContentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmListContentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmListContentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmListContentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmListContentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmListContentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cqlida::csmListContentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e5189348fab3e6087071660d62c9480";
  }

  static const char* value(const ::cqlida::csmListContentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e5189348fab3e60ULL;
  static const uint64_t static_value2 = 0x87071660d62c9480ULL;
};

template<class ContainerAllocator>
struct DataType< ::cqlida::csmListContentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/csmListContentRequest";
  }

  static const char* value(const ::cqlida::csmListContentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cqlida::csmListContentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 max_results\n\
";
  }

  static const char* value(const ::cqlida::csmListContentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cqlida::csmListContentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct csmListContentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cqlida::csmListContentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cqlida::csmListContentRequest_<ContainerAllocator>& v)
  {
    s << indent << "max_results: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_results);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CQLIDA_MESSAGE_CSMLISTCONTENTREQUEST_H
