// Generated by gencpp from file cqlida/csmListContentResponse.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CSMLISTCONTENTRESPONSE_H
#define CQLIDA_MESSAGE_CSMLISTCONTENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cqlida/KeyValues.h>

namespace cqlida
{
template <class ContainerAllocator>
struct csmListContentResponse_
{
  typedef csmListContentResponse_<ContainerAllocator> Type;

  csmListContentResponse_()
    : content()  {
    }
  csmListContentResponse_(const ContainerAllocator& _alloc)
    : content(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cqlida::KeyValues_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cqlida::KeyValues_<ContainerAllocator> >::other >  _content_type;
  _content_type content;




  typedef boost::shared_ptr< ::cqlida::csmListContentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cqlida::csmListContentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct csmListContentResponse_

typedef ::cqlida::csmListContentResponse_<std::allocator<void> > csmListContentResponse;

typedef boost::shared_ptr< ::cqlida::csmListContentResponse > csmListContentResponsePtr;
typedef boost::shared_ptr< ::cqlida::csmListContentResponse const> csmListContentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cqlida::csmListContentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cqlida::csmListContentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cqlida

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'cqlida': ['/home/stephen/Development/ccrg/Cryptoquip/src/cqlida/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmListContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::csmListContentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmListContentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::csmListContentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmListContentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::csmListContentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cqlida::csmListContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "365444ac37c2afa52a19e72487f3747b";
  }

  static const char* value(const ::cqlida::csmListContentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x365444ac37c2afa5ULL;
  static const uint64_t static_value2 = 0x2a19e72487f3747bULL;
};

template<class ContainerAllocator>
struct DataType< ::cqlida::csmListContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/csmListContentResponse";
  }

  static const char* value(const ::cqlida::csmListContentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cqlida::csmListContentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/KeyValues[] content\n\
\n\
\n\
================================================================================\n\
MSG: cqlida/KeyValues\n\
string key\n\
string[] values\n\
";
  }

  static const char* value(const ::cqlida::csmListContentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cqlida::csmListContentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct csmListContentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cqlida::csmListContentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cqlida::csmListContentResponse_<ContainerAllocator>& v)
  {
    s << indent << "content[]" << std::endl;
    for (size_t i = 0; i < v.content.size(); ++i)
    {
      s << indent << "  content[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cqlida::KeyValues_<ContainerAllocator> >::stream(s, indent + "    ", v.content[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CQLIDA_MESSAGE_CSMLISTCONTENTRESPONSE_H
