// Generated by gencpp from file cqlida/cueModuleRequest.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CUEMODULEREQUEST_H
#define CQLIDA_MESSAGE_CUEMODULEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cqlida/CognitiveContent.h>

namespace cqlida
{
template <class ContainerAllocator>
struct cueModuleRequest_
{
  typedef cueModuleRequest_<ContainerAllocator> Type;

  cueModuleRequest_()
    : cue()  {
    }
  cueModuleRequest_(const ContainerAllocator& _alloc)
    : cue(_alloc)  {
  (void)_alloc;
    }



   typedef  ::cqlida::CognitiveContent_<ContainerAllocator>  _cue_type;
  _cue_type cue;




  typedef boost::shared_ptr< ::cqlida::cueModuleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cqlida::cueModuleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cueModuleRequest_

typedef ::cqlida::cueModuleRequest_<std::allocator<void> > cueModuleRequest;

typedef boost::shared_ptr< ::cqlida::cueModuleRequest > cueModuleRequestPtr;
typedef boost::shared_ptr< ::cqlida::cueModuleRequest const> cueModuleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cqlida::cueModuleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cqlida::cueModuleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cqlida

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'cqlida': ['/home/stephen/Development/ccrg/Cryptoquip/src/cqlida/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::cueModuleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cqlida::cueModuleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::cueModuleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cqlida::cueModuleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::cueModuleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cqlida::cueModuleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cqlida::cueModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c83f5c4e4e0e20fbc174f4f058009476";
  }

  static const char* value(const ::cqlida::cueModuleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc83f5c4e4e0e20fbULL;
  static const uint64_t static_value2 = 0xc174f4f058009476ULL;
};

template<class ContainerAllocator>
struct DataType< ::cqlida::cueModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/cueModuleRequest";
  }

  static const char* value(const ::cqlida::cueModuleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cqlida::cueModuleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cqlida/CognitiveContent cue\n\
\n\
================================================================================\n\
MSG: cqlida/CognitiveContent\n\
Header header\n\
KeyValues[] elements\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cqlida/KeyValues\n\
string key\n\
string[] values\n\
";
  }

  static const char* value(const ::cqlida::cueModuleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cqlida::cueModuleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cueModuleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cqlida::cueModuleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cqlida::cueModuleRequest_<ContainerAllocator>& v)
  {
    s << indent << "cue: ";
    s << std::endl;
    Printer< ::cqlida::CognitiveContent_<ContainerAllocator> >::stream(s, indent + "  ", v.cue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CQLIDA_MESSAGE_CUEMODULEREQUEST_H
