// Generated by gencpp from file cqlida/cueModule.msg
// DO NOT EDIT!


#ifndef CQLIDA_MESSAGE_CUEMODULE_H
#define CQLIDA_MESSAGE_CUEMODULE_H

#include <ros/service_traits.h>


#include <cqlida/cueModuleRequest.h>
#include <cqlida/cueModuleResponse.h>


namespace cqlida
{

struct cueModule
{

typedef cueModuleRequest Request;
typedef cueModuleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cueModule
} // namespace cqlida


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cqlida::cueModule > {
  static const char* value()
  {
    return "09e7477070ec280047cf1b603087f753";
  }

  static const char* value(const ::cqlida::cueModule&) { return value(); }
};

template<>
struct DataType< ::cqlida::cueModule > {
  static const char* value()
  {
    return "cqlida/cueModule";
  }

  static const char* value(const ::cqlida::cueModule&) { return value(); }
};


// service_traits::MD5Sum< ::cqlida::cueModuleRequest> should match 
// service_traits::MD5Sum< ::cqlida::cueModule > 
template<>
struct MD5Sum< ::cqlida::cueModuleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cqlida::cueModule >::value();
  }
  static const char* value(const ::cqlida::cueModuleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cqlida::cueModuleRequest> should match 
// service_traits::DataType< ::cqlida::cueModule > 
template<>
struct DataType< ::cqlida::cueModuleRequest>
{
  static const char* value()
  {
    return DataType< ::cqlida::cueModule >::value();
  }
  static const char* value(const ::cqlida::cueModuleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cqlida::cueModuleResponse> should match 
// service_traits::MD5Sum< ::cqlida::cueModule > 
template<>
struct MD5Sum< ::cqlida::cueModuleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cqlida::cueModule >::value();
  }
  static const char* value(const ::cqlida::cueModuleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cqlida::cueModuleResponse> should match 
// service_traits::DataType< ::cqlida::cueModule > 
template<>
struct DataType< ::cqlida::cueModuleResponse>
{
  static const char* value()
  {
    return DataType< ::cqlida::cueModule >::value();
  }
  static const char* value(const ::cqlida::cueModuleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CQLIDA_MESSAGE_CUEMODULE_H
